### ISSUE TITLE
Нарізати іконку для різних розширень

### ISSUE THREAD

**Issue by eresid** [eresid/HabraQuestAndroid#3]
Нарізати іконку для наступних розширень:
mdpi (medium) ~160dpi
hdpi (high) ~240dpi
xhdpi (extra-high) ~320dpi
xxhdpi (extra-extra-high) ~480dpi
xxxhdpi (extra-extra-extra-high) ~640dpi

Ознайомитись з наступним матеріалом:
http://developer.android.com/guide/practices/screens_support.html

**Comment by alSaintUk** [comment]
зроблено
